name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Установка Docker и Docker Compose
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Шаг 2: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 3: Установить зависимости
      - name: Install dependencies for organizations-service
        run: |
          cd organizations-service
          npm install

      - name: Install dependencies for events-service
        run: |
          cd events-service
          npm install

      # Шаг 4: Собрать и протестировать organizations-service
      - name: Build and test organizations-service
        run: |
          cd organizations-service
          docker compose up --build -d
          docker compose exec -T organizations-service npm test

      # Шаг 5: Собрать и протестировать events-service
      - name: Build and test events-service
        run: |
          cd events-service
          docker compose up --build -d
          docker compose exec -T events-service npm test

      # Шаг 6: Остановить контейнеры после тестов
      - name: Stop containers
        run: |
          cd organizations-service
          docker compose down
          cd ../events-service
          docker compose down