name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and test Organizations Service
        run: |
          cd organizations-service
          npm install
          npm test

      - name: Install dependencies and test Events Service
        run: |
          cd events-service
          npm install
          npm test

      - name: Build and run Docker containers
        run: docker-compose up --build -d